#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                             101
#define IDR_MENU1                               103
#define IDD_DIALOG2                             104
#define IDI_ICON1                               106
#define IDR_MENU2                               108
#define IDD_DIFFTOOL                            109
#define IDC_PATH1                               1000
#define IDC_PATH2                               1001
#define IDC_ANALYZE                             1002
#define IDC_LIST1                               1003
#define IDC_STATUS                              1004
#define IDC_BROWSE1                             1005
#define IDC_BROWSE2                             1006
#define IDC_SRC                                 1006
#define IDC_DEST                                1007
#define IDC_GO                                  1007
#define IDC_LOGPATH                             1008
#define IDC_TOTALPOS                            1008
#define IDC_LOGBROWSE                           1009
#define IDC_TOTALPROGRESS                       1009
#define IDC_FILEPROGRESS                        1010
#define IDC_STATS                               1010
#define IDC_FILEPOS                             1011
#define IDC_MASKHELP                            1011
#define IDC_CHECK1                              1012
#define IDC_REMOTE_LABEL                        1013
#define IDC_IGNORE_DATE                         1014
#define IDC_IGNORE_MISSLOCAL                    1015
#define IDC_IGNORE_MISSREMOTE                   1016
#define IDC_IGNORE_SIZE                         1017
#define IDC_DEFBEHAVIOR                         1018
#define IDC_LOG                                 1019
#define IDC_INCLUDE_FILES                       1020
#define IDC_SYNC_FOLDERS                        1021
#define IDC_LOCAL_LABEL                         1023
#define IDC_INCLUDE_LABEL                       1025
#define IDC_CHECK2                              1027
#define IDC_EDIT1                               1028
#define IDC_SYNCHROPATHS                        1029
#define IDC_LOGGING                             1030
#define IDC_DEFACTIONLABEL                      1031
#define IDC_LOGFILENAMELABEL                    1032
#define IDC_BROWSE                              1035
#define IDC_DIFF                                1036
#define IDC_DIFFPARAMS                          1037
#define IDC_THROTTLELBL                         1037
#define IDC_DRIVER                              40001
#define IDM_2TO1                                40001
#define IDM_1TO2                                40002
#define IDM_NOACTION                            40003
#define IDM_LOAD_SYNC_SETTINGS                  40004
#define IDM_SAVE_SYNC_SETTINGS                  40005
#define IDM_EXIT                                40006
#define IDM_ABOUT                               40007
#define IDM_OPENLOCAL                           40008
#define IDM_OPENREMOTE                          40009
#define IDM_DIFF                                40010
#define IDC_SETCOMPARE                          40011
